name: Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod tidy
      - name: Install mockery
        run: make install-mockery
      - name: Generate mocks
        run: make generate-mocks
      - name: Run unit tests
        run: |
          go test -tags=unit ./...
